INSERT INTO AUTHOR (ID, FIO)
VALUES (1, 'Peter Watts test author');
INSERT INTO AUTHOR (ID, FIO)
VALUES (2, 'MARIA TEST AUTHOR');
INSERT INTO AUTHOR (ID, FIO)
VALUES (3, 'IVAN TEST AUTHOR');
INSERT INTO AUTHOR (ID, FIO)
VALUES (4, 'PELEVIN TEST AUTHOR');
INSERT INTO AUTHOR (ID, FIO)
VALUES (5, 'DOSTOEVSKIY TEST AUTHOR');
INSERT INTO AUTHOR (ID, FIO)
VALUES (6, 'TOLSTOY TEST AUTHOR');
INSERT INTO AUTHOR (ID, FIO)
VALUES (7, 'NON RELATED TEST AUTHOR');

INSERT INTO GENRE (ID, CAPTION)
VALUES (1, 'HORROR TEST GENRE');
INSERT INTO GENRE (ID, CAPTION)
VALUES (2, 'FANTASY TEST GENRE');
INSERT INTO GENRE (ID, CAPTION)
VALUES (3, 'SKY-FI TEST GENRE');
INSERT INTO GENRE (ID, CAPTION)
VALUES (4, 'NON RELATED TEST GENRE');

INSERT INTO BOOK (ID, BOOK_NAME, ID_GENRE)
VALUES (1, 'HORROR TEST BOOK', 1);
INSERT INTO BOOK (ID, BOOK_NAME, ID_GENRE)
VALUES (2, 'FANTASY TEST BOOK', 2);
INSERT INTO BOOK (ID, BOOK_NAME, ID_GENRE)
VALUES (3, 'SKY-FI TEST BOOK', 3);

INSERT INTO BOOK_AUTHOR (ID_BOOK, ID_AUTHOR)
VALUES (1, 1);
INSERT INTO BOOK_AUTHOR (ID_BOOK, ID_AUTHOR)
VALUES (1, 2);
INSERT INTO BOOK_AUTHOR (ID_BOOK, ID_AUTHOR)
VALUES (1, 3);
INSERT INTO BOOK_AUTHOR (ID_BOOK, ID_AUTHOR)
VALUES (1, 4);
INSERT INTO BOOK_AUTHOR (ID_BOOK, ID_AUTHOR)
VALUES (2, 5);
INSERT INTO BOOK_AUTHOR (ID_BOOK, ID_AUTHOR)
VALUES (2, 6);
INSERT INTO BOOK_AUTHOR (ID_BOOK, ID_AUTHOR)
VALUES (3, 1);