INSERT INTO AUTHOR (ID, FIO)
VALUES (1, 'Peter Watts');
INSERT INTO AUTHOR (ID, FIO)
VALUES (2, 'Robert Hainline');
INSERT INTO AUTHOR (ID, FIO)
VALUES (3, 'Arkady and Boris Strugatsky');
INSERT INTO AUTHOR (ID, FIO)
VALUES (4, 'Vernor Vinge');

INSERT INTO GENRE (ID, CAPTION)
VALUES (1, 'Horror');
INSERT INTO GENRE (ID, CAPTION)
VALUES (2, 'Fantasy');
INSERT INTO GENRE (ID, CAPTION)
VALUES (3, 'Sci-Fi');

INSERT INTO BOOK (ID, BOOK_NAME, ID_GENRE, ID_AUTHOR)
VALUES (1, 'Blindsight', 3, 1);
INSERT INTO BOOK (ID, BOOK_NAME, ID_GENRE, ID_AUTHOR)
VALUES (2, 'The Moon Is a Harsh Mistress', 3, 2);
INSERT INTO BOOK (ID, BOOK_NAME, ID_GENRE, ID_AUTHOR)
VALUES (3, 'Prisoners of Power', 2, 3);