INSERT INTO AUTHOR (ID, FIO)
VALUES (1, 'Peter Watts');
INSERT INTO AUTHOR (ID, FIO)
VALUES (2, 'ANTONY');
INSERT INTO AUTHOR (ID, FIO)
VALUES (3, 'IVAN');
INSERT INTO AUTHOR (ID, FIO)
VALUES (4, 'PELEVIN');
INSERT INTO AUTHOR (ID, FIO)
VALUES (5, 'DOSTOEVSKIY');
INSERT INTO AUTHOR (ID, FIO)
VALUES (6, 'TOLSTOY');

INSERT INTO GENRE (ID, CAPTION)
VALUES (1, 'HORROR');
INSERT INTO GENRE (ID, CAPTION)
VALUES (2, 'FANTASY');
INSERT INTO GENRE (ID, CAPTION)
VALUES (3, 'SKY-FI');

INSERT INTO BOOK (ID, BOOK_NAME, ID_GENRE)
VALUES (1, 'HORROR BOOK', 1);
INSERT INTO BOOK (ID, BOOK_NAME, ID_GENRE)
VALUES (2, 'FANTASY BOOK', 2);
INSERT INTO BOOK (ID, BOOK_NAME, ID_GENRE)
VALUES (3, 'SKY-FI BOOK', 3);

INSERT INTO BOOK_AUTHOR (ID_BOOK, ID_AUTHOR)
VALUES (1, 1);
INSERT INTO BOOK_AUTHOR (ID_BOOK, ID_AUTHOR)
VALUES (1, 2);
INSERT INTO BOOK_AUTHOR (ID_BOOK, ID_AUTHOR)
VALUES (1, 3);
INSERT INTO BOOK_AUTHOR (ID_BOOK, ID_AUTHOR)
VALUES (1, 4);
INSERT INTO BOOK_AUTHOR (ID_BOOK, ID_AUTHOR)
VALUES (2, 5);
INSERT INTO BOOK_AUTHOR (ID_BOOK, ID_AUTHOR)
VALUES (2, 6);
INSERT INTO BOOK_AUTHOR (ID_BOOK, ID_AUTHOR)
VALUES (3, 1);