DROP TABLE IF EXISTS AUTHOR;
CREATE TABLE AUTHOR
(
    ID  BIGINT AUTO_INCREMENT PRIMARY KEY,
    FIO VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS GENRE;
CREATE TABLE GENRE
(
    ID      BIGINT AUTO_INCREMENT PRIMARY KEY,
    CAPTION VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS BOOK;
CREATE TABLE BOOK
(
    ID       BIGINT AUTO_INCREMENT PRIMARY KEY,
    BOOK_NAME VARCHAR(255) NOT NULL,
    ID_GENRE BIGINT(255) NOT NULL
);

DROP TABLE IF EXISTS BOOK_AUTHOR;
CREATE TABLE BOOK_AUTHOR
(
    ID_BOOK   BIGINT,
    ID_AUTHOR BIGINT,
    PRIMARY KEY (ID_BOOK, ID_AUTHOR),
    foreign key (ID_BOOK) references BOOK (ID),
    foreign key (ID_AUTHOR) references AUTHOR (ID)
);