DROP TABLE IF EXISTS AUTHOR;
CREATE TABLE AUTHOR
(
    ID  BIGINT AUTO_INCREMENT PRIMARY KEY,
    FIO VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS GENRE;
CREATE TABLE GENRE
(
    ID      BIGINT AUTO_INCREMENT PRIMARY KEY,
    CAPTION VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS BOOK;
CREATE TABLE BOOK
(
    ID       BIGINT AUTO_INCREMENT PRIMARY KEY,
    BOOK_NAME VARCHAR(255) NOT NULL,
    ID_GENRE BIGINT(255) NOT NULL,
    ID_AUTHOR BIGINT(255) NOT NULL,
    foreign key (ID_GENRE) references GENRE (ID),
    foreign key (ID_AUTHOR) references AUTHOR (ID)
);