logging:
  file:
    path: './logs'
    name: ${logging.file.path}/app.log

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    initialization-mode: always
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    show-sql: false
  shell:
    command:
      stacktrace:
        enabled: false