logging:
  file:
    path: './logs'
    name: ${logging.file.path}/app.log

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/library
  shell:
    command:
      stacktrace:
        enabled: false

mongock:
  runner-type: applicationrunner
  change-logs-scan-package:
    - ru.otus.library.mongock.changelog


